services:

  demand_service:
    build: ./services/demand
    container_name: demand_service

  supply_service:
    build: ./services/supply
    container_name: supply_service

  surge_service:
    build: ./services/surge
    container_name: surge_service
    depends_on:
      - demand_service
      - supply_service

  redis:
    image: redis:latest
    container_name: surge_redis
    ports:
      - "6379:6379"