name: US-005 Automation Pipeline

on:
  push:
    branches:
      - feature/automation-pipeline
      - main
      - DEV
  pull_request:
    branches:
      - feature/automation-pipeline
      - main
      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      - name: Build Docker Containers
        run: docker compose build n